/**
 * Centralized error code constants.
 * Maps to HTTP status codes and error messages used across the service.
 */
const ErrorCodes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BALANCE_NOT_FOUND: 'BALANCE_NOT_FOUND',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INSUFFICIENT_LOCAL_BALANCE: 'INSUFFICIENT_LOCAL_BALANCE',
  INSUFFICIENT_HCM_BALANCE: 'INSUFFICIENT_HCM_BALANCE',
  INSUFFICIENT_EFFECTIVE_BALANCE: 'INSUFFICIENT_EFFECTIVE_BALANCE',
  INVALID_DIMENSIONS: 'INVALID_DIMENSIONS',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  HCM_UNAVAILABLE: 'HCM_UNAVAILABLE',
  HCM_TIMEOUT: 'HCM_TIMEOUT',
  HCM_SUBMISSION_FAILED: 'HCM_SUBMISSION_FAILED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
});

module.exports = { ErrorCodes };
